# Generated by Django 4.2.30 on 2026-04-13 13:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('file_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='services.service')),
            ],
        ),
    ]
